### ISSUE TITLE
Enhancement: CSV Based Filter

### ISSUE THREAD

**Issue by ramarnat** [hoshsadiq/m3ufilter#14]
I would like to suggest a way to specify an input csv file to batch filter/set individual streams:

```yaml
core:
  server_listen: localhost:8080
  update_schedule: "*/24 * * * *"
  output: m3u
  group_order:
    - Entertainment
    - Family/Kids
    - News
    - Drama
providers:
  - uri: file:///path/to/m3u/playlist.m3u
    csv_filter: file:///path/to/m3u/filter.csv
    csv_setter:
        - Id: tvg_id_csv_col
        csv_filter_field: CUID_csv_col
```

what do you think @hoshsadiq ?
