### ISSUE TITLE
Channels are mixed

### ISSUE THREAD

**Issue by Surfoo** [hoshsadiq/m3ufilter#17]
Hello,

I would like to remove almost all groups from the original m3u but in the output, channels are mixed (French and USA channels).

Here my config:

```
providers:
  - uri: http://randomurl.com
    filters:
        - match(Group, "EU FRANCE FULL HD") || match(Group, "^USA$")
```

Is my configuration wrong?
