### ISSUE TITLE
[FEATURE] Ability to filter based on tvg-language field

### ISSUE THREAD

**Issue by emlimap** [hoshsadiq/m3ufilter#26]
**Is your feature request related to a problem? Please describe.**

IPTV repo (https://github.com/iptv-org/iptv) provides m3u lists for each country and each entry has a language attribute (tvg-language) and would like to filter based on it. 

In some countries where there is more than one spoken language, for example India, there are a lot of IPTV entries for various languages and would like to filter to include the ones I want.

**Describe the solution you'd like**

m3ufilter is able to parse `tvg-language` field from m3u (example: https://github.com/iptv-org/iptv/blob/master/channels/in.m3u) and filter based on language. 

For example, the filtering config would look something like below

```
providers:
  - uri: https://raw.githubusercontent.com/iptv-org/iptv/master/channels/in.m3u
    filters:
     - match(language, "English")
     - match(language, "Tamil")
```

**Describe alternatives you've considered**

One alternative I have considered is to take the per language list provided by the project (https://github.com/iptv-org/iptv/blob/master/README.md#playlists-by-language) and merge them before passing it on to m3ufilter.
