### ISSUE TITLE
Operator using YAML to filter channels

### ISSUE THREAD

**Issue by Pcsl** [hoshsadiq/m3ufilter#34]
This is not really a bug nor a feature request, as the only thing I need is some help to set up the config file as I'm having serious problems to understand how to work with YAML. What I'm trying is to remove from my list channels that end with mkv (as they are just movies and not real live channels.

I tried following your config file but it says the syntax is not correct when using: - !match(Uri, "mkv").

This is my code:

```
core:
  server_listen: localhost:8090
  update_schedule: "*/24 * * * *"
  output: m3u
  group_order:
    - Entertainment
    - Family/Kids
    - News
    - Drama
providers:
  - uri: myserverurl
    filters:
      - !match(Uri, "mkv")
    setters:
      - name: replace(Name, "[\\s\\:\\|]+", " ")
      - name: replace(Name, "^VIP ", "")
      - name: replace(Name, "USA", "")
        attributes:
          tvg-id: tvg_id(Name) + ".us"
        filters:
          - Name == "USA CNN"
          - Name == "CNN"
          - Name == "CNN HD"
epg_providers:
  - uri: myserverurl
    channel_id_renames:
      replacement: find # key = what to replace it with, value = what to find
      bbc.uk: "BBC One"
```
